services:
  app:
    build: ./
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=3000
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: always
