services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: always
